version: '3.8'
services:
  mysql:
    image: mysql:oracle
    container_name: mysql
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
    ports:
      - 3306:3306
    networks:
      - default
    volumes:
      - mysql_data:/var/lib/mysql

  php-apache:
    container_name: php-apache
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src/:/var/www/html/
    ports:
      - 8081:80
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
    stdin_open: true
    tty: true
    depends_on:
      - mysql
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8080:80
    restart: always
    environment:
      PMA_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql
    networks:
      - default

volumes:
  mysql_data:
