version: '3.8'
services:
  mysql:
    image: mysql:8.0-bullseye
    container_name: mysql
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - default
    volumes:
      - mysql_data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql

  php-apache:
    container_name: php-apache
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src/:/var/www/html/
    ports:
      - ${APACHE_PORT}:80
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      APACHE_PORT: ${APACHE_PORT}
      DEV_MODE: true
    stdin_open: true
    tty: true
    depends_on:
      - mysql
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - ${PHPMYADMIN_PORT}:80
    restart: always
    environment:
      PMA_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PHPMYADMIN_PORT: ${PHPMYADMIN_PORT}
    depends_on:
      - mysql
    networks:
      - default

volumes:
  mysql_data:
