on: push
name: 🚀 Deploy with FTP on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server-dir: public_html/
          local-dir: src/
          server: ftp.okudumanladim.com
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          protocol: ftp
          port: 21
          log-level: minimal
          security: strict
          timeout: 60000
          dangerous-clean-slate: true
          dry-run: true
          exclude: |
            **/.env*
            **/.git*
            **/.git*/**
            **/.docker*
            **/docker*
            **/node_modules/**
